" Hidden GUI {{{

" Hidden Toolbar
set guioptions-=T

" Hidden Menubar
set guioptions-=m

" Hidden Right scrollbar
set guioptions-=r
set guioptions-=R

" Hidden Left scrollbar
set guioptions-=l
set guioptions-=L

" Hidden Bottom scrollbar
set guioptions-=b

" }}}

" Fullscreen {{{
nnoremap <F11> :call ToggleFullScreen()<CR>
function! ToggleFullScreen()
  if &guioptions =~# 'C'
    set guioptions-=C
    if exists('s:go_temp')
      if s:go_temp =~# 'm'
        set guioptions+=m
      endif
      if s:go_temp =~# 'T'
        set guioptions+=T
      endif
    endif
    simalt ~r
  else
    let s:go_temp = &guioptions
    set guioptions+=C
    set guioptions-=m
    set guioptions-=T
    simalt ~x
  endif
endfunction
" }}}

" GUI Appearance {{{

set guifont=Ricty:h16
colorscheme hybrid

" }}}

" {{{
set clipboard+=unnamed
" }}}
