" Localize
source ~/foundation/vim/vimrc.d/localize.vimrc

" Neobundle
source ~/foundation/vim/vimrc.d/neobundle.vimrc

" General
source ~/foundation/vim/vimrc.d/general.vimrc

" Apprarance
source ~/foundation/vim/vimrc.d/appearance.vimrc

" Search
source ~/foundation/vim/vimrc.d/search.vimrc

" Keys
source ~/foundation/vim/vimrc.d/keys.vimrc
