" Neobundle
source ~/dotfiles/.vimrc.d/neobundle.vimrc

" General
source ~/dotfiles/.vimrc.d/general.vimrc

" Apprarance
source ~/dotfiles/.vimrc.d/appearance.vimrc

" Search
source ~/dotfiles/.vimrc.d/search.vimrc

" Keys
source ~/dotfiles/.vimrc.d/keys.vimrc

" Unite
source ~/dotfiles/.vimrc.d/unite.vimrc

" Vimfiler
source ~/dotfiles/.vimrc.d/vimfiler.vimrc

" Neocomplcache
source ~/dotfiles/.vimrc.d/neocomplcache.vimrc
