# language setting
export LANG=C

# export PATH for homebrew
export PATH=/usr/local/bin/:/usr/local/sbin/:$PATH

# init rbenv
if [ -f ~/.rbenv/bin/rbenv ]; then
	export PATH=~/.rbenv/bin:$PATH
fi
type rbenv > /dev/null 2>&1 && eval "$(rbenv init -)"

# init phpenv
if [ -f ~/.phpenv/bin/phpenv ]; then
	export PATH=~/.phpenv/bin:$PATH
fi
type phpenv > /dev/null 2>&1 && eval "$(phpenv init -)"

# init nvm
if [ -f ~/.nvm/nvm.sh ]; then
	. ~/.nvm/nvm.sh
fi


source ~/.env.d/*

export VIM_ROOT=/Users/tamurine/.vim
