# Path to your oh-my-zsh installation.
export ZSH=$HOME/src/github.com/robbyrussell/oh-my-zsh

ZSH_THEME="ys"

ZSH_CUSTOM=$HOME/.zcustom

plugins=(git)

source $ZSH/oh-my-zsh.sh

# history
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end
